'use client';

import React from 'react';
import styles from './SolvedExamples.module.css';

export interface ExampleData {
  id: number;
  question: string;
  given: string[];
  formula: string;
  solutionSteps: string[];
  answer: string;
  realLife?: string;
  visualizerImage?: string; // High tech image generated by Nano Banana for the numerical concept
}

interface SolvedExamplesProps {
  title: string;
  examples: ExampleData[];
}

export default function SolvedExamples({ title, examples }: SolvedExamplesProps) {
  return (
    <div className={styles.container}>
      <h3 className={styles.mainTitle}>{title}</h3>
      <div className={styles.examplesGrid}>
        {examples.map((ex) => (
          <div key={ex.id} className={styles.exampleCard}>
            
            {ex.visualizerImage && (
              <div className={styles.visualizerContainer} style={{ width: '100%', borderRadius: '8px', overflow: 'hidden', marginBottom: '15px', border: '1px solid rgba(0, 255, 204, 0.3)', boxShadow: '0 4px 15px rgba(0,0,0,0.5)' }}>
                <img src={ex.visualizerImage} alt={`Concept Visualizer for Example ${ex.id}`} style={{ width: '100%', height: 'auto', display: 'block', objectFit: 'cover', maxHeight: '250px' }} />
                <div style={{ background: 'rgba(0,0,0,0.8)', padding: '5px 10px', fontSize: '0.75rem', color: '#00ffcc', textAlign: 'center', textTransform: 'uppercase', letterSpacing: '1px' }}>
                  Concept Visualizer
                </div>
              </div>
            )}

            <div className={styles.questionBox}>
              <span className={styles.badge}>Example {ex.id}</span>
              <p className={styles.question}>{ex.question}</p>
            </div>
            
            <div className={styles.solutionBox}>
              <div className={styles.givenSection}>
                <strong>Given:</strong>
                <ul>
                  {ex.given.map((g, i) => <li key={i}>{g}</li>)}
                </ul>
              </div>

              <div className={styles.formulaSection}>
                <strong>Formula Used:</strong>
                <code className={styles.formula}>{ex.formula}</code>
              </div>

              <div className={styles.stepsSection}>
                <strong>Solution Steps:</strong>
                <ol>
                  {ex.solutionSteps.map((step, i) => <li key={i}>{step}</li>)}
                </ol>
              </div>

              <div className={styles.answerSection}>
                <strong>Final Answer:</strong>
                <span className={styles.answer}>{ex.answer}</span>
              </div>

              {ex.realLife && (
                <div className={styles.realLifeSection}>
                  <strong>Real-Life Context:</strong>
                  <p>{ex.realLife}</p>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
